### PR TITLE
Support comments starting with '#' next to ';'

### PR DESCRIPTION
**Pull request by nxadm**
Hi,

On UNIX (-like) systems is it customary to support comments starting with '#' instead of ';' for config INI files. This PR adds support for discarding lines starting with # as comments.

C.

### CODE REVIEW

**Comment by tadzik** [comment]
Looks good to me. Can we get some tests just in case?

**Comment by nxadm** [comment]
I'll add it to my todo list to add tests for it.

**Comment by tadzik** [comment]
Awesome, thank you!

**Comment by nxadm** [comment]
Tests added for the PR changes.

**Comment by tadzik** [comment]
Looks good, thanks a lot :) And sorry to keep you waiting!

**Comment by nxadm** [comment]
Great news! I  can now remove the local fork in my application :)

**Pull request merged**
